In [15]:
import torch
from torch import nn, optim
import torchvision
from torchvision import transforms, datasets, models, utils
from torch.utils.data import Dataset, DataLoader 
from PIL import Image
from sklearn.model_selection import train_test_split
from torch.nn import functional as F
from skimage import io, transform
from torch.optim import lr_scheduler
from skimage.transform import AffineTransform, warp
from sklearn.metrics import roc_auc_score, mean_absolute_error

import pandas as pd
from pathlib import Path
import os
import cv2
import matplotlib.pyplot as plt
import numpy as np
import random

INPUT_PATH = Path('../input')
OUTPUT_PATH = Path('../output')
TRAIN_PATH = INPUT_PATH / 'idao_dataset' / 'train'
PRIVATE_PATH = INPUT_PATH / 'idao_dataset' / 'private_test'
PUBLIC_PATH = INPUT_PATH / 'idao_dataset' / 'private_test'

RANDOM_SEED = 4444
def seed_everything(seed=1234):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
seed_everything(RANDOM_SEED)

In [18]:
preds = pd.read_csv(INPUT_PATH / 'predictions.csv')

preds['classification_predictions'] = preds['classification_predictions'].map({0:1, 1:0})
preds.to_csv(OUTPUT_PATH / 'sub.csv', index = None)

In [20]:
preds

,id,classification_predictions,regression_predictions
0,1094c735a996424ee7584211e295686e227ceaf0,1,12.314678
1,8cf933ace1253fb9f2205ac8d136c16414660b69,1,14.162201
2,1c6c4bfd59f364a760dec049d7248f27064704b4,1,11.142391
3,a607ab02ad92d5edea271fb26f1dcc8068614d7f,0,14.578810
4,d645b4a860c18486559e6798ffac44a86d91e1a3,1,13.691868
...,...,...,...
16559,47baff216659d41d87bbb44c5b856332f1148419,0,22.035202
16560,ed6bf88e668dc8a197f284d1b693d2bad6098184,1,9.863609
16561,21c47f62d1f25562cdb19ed84ea41e69cc1686a6,1,12.230904
16562,787368ee4650c49478fcbc99763fc5960beece38,1,10.236641
16563,899faf9733cfabc6d0fe73213e9653882d92f426,1,13.353785